# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d42aace3c8b1a7944e489ccd3761f2deef0d00d2f213652abb426dc5cd9bab5e00eda8ed21c33428b9ad226bea4390e64607ac486ea1a4c6fa744c75dc854e8

test:
  secret_key_base: 23f237fa7a507d726db42ea3a8eb2e463431b185ad79b350a7d6082d6c010d3cd6efa2331750a8e4806bf9b1985bbcc529dc5fb8eacd3bde5b441ba247ebf7cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
